# Variables:
#   SITE_URL: The URL of the deployed site.
name: CI
on:
  push:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build-site:
    name: Build Site
    if: |
      vars.SITE_URL != ''
    runs-on: ubuntu-latest
    env:
      SITE_URL: ${{ vars.SITE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-
          path: |
            ~/.cache/deno
      - name: Install Dependencies
        run: deno install
      - name: Build Site
        run: deno task build
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs: [build-site]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
